// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSq3sXTfcuMq-EPSNdwd3lXxqrVxvzgLE',
    appId: '1:222693628192:web:bae324e5444ca3838adf45',
    messagingSenderId: '222693628192',
    projectId: 'uff-mobile-plus',
    authDomain: 'uff-mobile-plus.firebaseapp.com',
    databaseURL: 'https://uff-mobile-plus.firebaseio.com',
    storageBucket: 'uff-mobile-plus.firebasestorage.app',
    measurementId: 'G-WPPH8SSRQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIe3CCE33ya8jACc23P8nIIDp-L1GK_gE',
    appId: '1:222693628192:android:513f83091d5400ac8adf45',
    messagingSenderId: '222693628192',
    projectId: 'uff-mobile-plus',
    databaseURL: 'https://uff-mobile-plus.firebaseio.com',
    storageBucket: 'uff-mobile-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIA_27Ff9I_M5YKFJGC9IPgVG4d8dmSFw',
    appId: '1:222693628192:ios:20432ec8de50689f8adf45',
    messagingSenderId: '222693628192',
    projectId: 'uff-mobile-plus',
    databaseURL: 'https://uff-mobile-plus.firebaseio.com',
    storageBucket: 'uff-mobile-plus.firebasestorage.app',
    androidClientId: '222693628192-0aho0srg8evnbobvdb118ptmsjc5jacc.apps.googleusercontent.com',
    iosClientId: '222693628192-jiakuaaa00i9o5ov8kfcmnopq24slr6h.apps.googleusercontent.com',
    iosBundleId: 'br.uff.uffmobileplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIA_27Ff9I_M5YKFJGC9IPgVG4d8dmSFw',
    appId: '1:222693628192:ios:20432ec8de50689f8adf45',
    messagingSenderId: '222693628192',
    projectId: 'uff-mobile-plus',
    databaseURL: 'https://uff-mobile-plus.firebaseio.com',
    storageBucket: 'uff-mobile-plus.firebasestorage.app',
    androidClientId: '222693628192-0aho0srg8evnbobvdb118ptmsjc5jacc.apps.googleusercontent.com',
    iosClientId: '222693628192-jiakuaaa00i9o5ov8kfcmnopq24slr6h.apps.googleusercontent.com',
    iosBundleId: 'br.uff.uffmobileplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSq3sXTfcuMq-EPSNdwd3lXxqrVxvzgLE',
    appId: '1:222693628192:web:51031092cad897918adf45',
    messagingSenderId: '222693628192',
    projectId: 'uff-mobile-plus',
    authDomain: 'uff-mobile-plus.firebaseapp.com',
    databaseURL: 'https://uff-mobile-plus.firebaseio.com',
    storageBucket: 'uff-mobile-plus.firebasestorage.app',
    measurementId: 'G-82JNHMZEE7',
  );
}
